# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test1:
    name: AddingWords
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testAddingWords test


  test2:
    name: ContainsNotAddedWords
    runs-on: ubuntu-latest
    steps:
      - name: Test 2
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testContainsNotAddedWords test

  test3:
    name: ContainsNull
    runs-on: ubuntu-latest
    steps:
      - name: Test 3
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testContainsNull test

  test4:
    name: AddNull
    runs-on: ubuntu-latest
    steps:
      - name: Test 4
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testAddNull test

  test5:
    name: AddEmptyString
    runs-on: ubuntu-latest
    steps:
      - name: Test 5
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testAddEmptyString test

  test6:
    name: AddAlreadyAddedWord
    runs-on: ubuntu-latest
    steps:
      - name: Test 6
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testAddAlreadyAddedWord test

  test7:
    name: ContainsEmptyString
    runs-on: ubuntu-latest
    steps:
      - name: Test 7
        uses: actions/checkout@v3
      - run: mvn test -Dtest=PrefixTreeTest#testContainsEmptyString test

